feat(swap): adapting the swap with an interface ISwap
morpho-org/morpho-blue-snippets pull request #16
Opened 2023-11-21 08:12 UTC by tomrpl

adapting the swap on the callback contract with an ISwap interface

2023-11-22 09:08 UTC, julien-devatom requested changes
"mock" is an implementation, not an interface. The naming of the interface should correspond to the expected behavior of the contract. Here, it is a swapper.

2023-11-22 09:08 UTC, julien-devatom commented on src/blue/CallbacksSnippets.sol
> +    ISwap public swapMock;
```suggestion
    ISwap public immutable swapper;
```

2023-11-22 09:08 UTC, julien-devatom commented on src/blue/CallbacksSnippets.sol
> +    }
```suggestion
    constructor(IMorpho _morpho, ISwap _swapper) {
        morpho = _morpho;
        swapper = _swapper;
    }
```

2023-11-22 09:38 UTC, tomrpl commented
Adapting tests: they are passing ✅

2023-11-24 10:25 UTC, julien-devatom approved these changes

2023-11-24 15:31 UTC, merged