feat(metamorpho): add reallocate idle snippet
morpho-org/morpho-blue-snippets pull request #40
Opened 2024-01-10 10:16 UTC by Rubilmax

2024-01-10 11:26 UTC, tomrpl commented on src/metamorpho/MetaMorphoSnippets.sol
> +    function reallocateAvailableLiquidity(
anything we want to add in the description of the function? 
otherwise good to me IMO

2024-01-10 17:08 UTC, Jean-Grimal requested changes

2024-01-10 17:08 UTC, Jean-Grimal commented on src/metamorpho/MetaMorphoSnippets.sol
> +                assets: availableLiquidity >= supplyAssets ? 0 : availableLiquidity
I think you got it wrong
```suggestion
                assets: availableLiquidity >= supplyAssets ? 0 : supplyAssets.zeroFloorSub(availableLiquidity)
```

2024-01-10 18:24 UTC, Rubilmax commented on src/metamorpho/MetaMorphoSnippets.sol
> +                assets: availableLiquidity >= supplyAssets ? 0 : availableLiquidity
```suggestion
                assets: supplyAssets.zeroFloorSub(availableLiquidity)
```

2024-01-12 10:34 UTC, Jean-Grimal approved these changes
LGTM,
I surprisingly didn't had to modify the tests because as `1 ether` is supplied and `0.5 ether` is borrowed, we have `supplyAssets.zeroFloorSub(availableLiquidity)` = ` 1 ether - 0.5 ether` = `0.5 ether` = `availableLiquidity`

2024-01-12 12:53 UTC, Rubilmax reviewed
LGTM!

2024-01-12 12:53 UTC, Rubilmax commented on src/metamorpho/MetaMorphoSnippets.sol
> +    /// assets into srcMarketParams.
```suggestion
    /// assets into destMarketParams.
```

2024-01-12 13:03 UTC, merged

2024-01-12 13:16 UTC, MerlinEgalite commented
Please @Jean-Grimal wait my review before merging it.

2024-01-12 13:42 UTC, MerlinEgalite commented on src/metamorpho/MetaMorphoSnippets.sol
> +    /// @dev The snippets contract must be registered as an allocator of the vault for the fuction to be called
typo: fuction -> function

2024-01-12 13:42 UTC, MerlinEgalite commented on src/metamorpho/MetaMorphoSnippets.sol
> +    /// @param srcMarketParams The market parameters of the markets to withdraw from.
this is a list of marketParams that is passed as argument so the comment is not accurate