feat(HF): simulating repayment-borrow actions and exposing the healthFactor
morpho-org/morpho-blue-snippets pull request #55
Opened 2024-08-28 07:19 UTC by tomrpl

Here is the first iteration of the virtual repayment/borrow.

With Merlin, we discussed abut the fact that having assets only in input is enough in the current requirement from the integrator that requested it.

Would you mind spend some time thinking about potential hedge case that would break the computation? 

Tried to cover some in our test.

To get them pass, I had to bound the borrowedAmount with the MAX_AMOUNT being MAX_TEST_AMOUNT/2 instead of letting to MAX_TEST_AMOUNT.

Do you have a workaround in mind @Rubilmax ?

Thank you guys!

2024-08-28 07:28 UTC, MerlinEgalite requested changes

2024-08-28 07:28 UTC, MerlinEgalite commented on src/morpho-blue/MorphoBlueSnippets.sol
> +    }
I would extract the logic into another contract tbh as we don't care about the rest of the logic

2024-08-28 07:28 UTC, MerlinEgalite commented on src/morpho-blue/MorphoBlueSnippets.sol
> +        uint256 newBorrowed = borrowed > repaymentAmount ? borrowed - repaymentAmount : 0;
I would revert in this case instead (safer)

2024-08-28 07:28 UTC, MerlinEgalite commented on src/morpho-blue/MorphoBlueSnippets.sol
> +        require(newBorrowed >= borrowed, "Borrow amount overflow");
There's no overflow possible as we're using solidity 0.8.x

If `borrowed + borrowAmount` is too large it will revert

2024-08-28 12:25 UTC, MerlinEgalite commented on src/morpho-blue/VirtualHealthFactor.sol
> +    }
could be a constant maybe?

2024-08-28 12:44 UTC, tomrpl commented on src/morpho-blue/VirtualHealthFactor.sol
> +    }
I think that is not necessary. 
I'll let that open for Romain to see it, no strong opinion on my side though

2024-09-05 07:46 UTC, Rubilmax approved these changes
Looks good

Take a look at: https://morpholabs.slack.com/archives/C02P3QE2Q8G/p1725447118759289

You have no new line at EOF in tests (hence the 🚫 symbol in github reviews)

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +    }
Not either, snippets are here to should how to interact with it imo not how to store information

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +    function userHealthFactorAfterVirtualRepayment(
```suggestion
    function userHypotheticalHealthFactor(
```

just a suggestion, current naming is expressive neough

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +        uint256 repaymentAmount
```suggestion
        uint256 repaidAssets
```

to keep naming consistent with Morpho Blue

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +        returns (uint256 healthFactor)
```suggestion
        returns (uint256)
```

Return statements are clearer but idrc

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +    ) public view returns (uint256 healthFactor) {
```suggestion
    ) public view returns (uint256) {
```

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +        require(repaymentAmount <= borrowed, "Repayment amount exceeds borrowed amount");
We could simply let the snippet revert with underflow just like in Morpho Blue (idrc)

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +        uint256 newBorrowed = borrowed + borrowAmount;
Note here you can overflow for a similar reason than during repay. Yet we don't revert with a dedicated message in this case (inconsistency). I would prefer not reverting during repay

2024-09-05 07:46 UTC, Rubilmax commented on src/morpho-blue/VirtualHealthFactor.sol
> +    function userHealthFactorAfterVirtualRepayment(
```suggestion
    function userHealthFactorAfterVirtualRepay(
```

This is more consistent with the borrow naming

2024-10-03 14:11 UTC, merged